## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [14]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [15]:
n_class_0, n_class_1

(900, 100)

In [16]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [17]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [18]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [19]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [41]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

# 1. Upsampling

In [40]:
df_minority=df[df['target']==1]

In [22]:
df_majority=df[df['target']==0]

In [24]:
from sklearn.utils import resample
df_minority_upsampled =resample(df_minority,replace=True,
                n_samples=len(df_majority),
                random_state=42
        )

In [25]:
df_minority_upsampled.shape

(900, 3)

In [26]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [28]:
df_unsampled=pd.concat([df_majority, df_minority_upsampled])

In [29]:
df_unsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

# 2. Downsampling
not recommended as it affects the data quality (removing from the dataset that has a lot of values)

In [30]:
## Down Scaling
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [31]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [32]:
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [33]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [36]:
df_majority_downsampled =resample(df_majority,replace=False,
                n_samples=len(df_minority),
                random_state=42
        )

In [37]:
df_majority_downsampled.shape

(100, 3)

In [38]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [39]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64